---
- hosts: all
  become: yes
  tasks:
  - name: i want to ping all my hosts or nodes
    ping:

  - name: i want to install apache2 webserver on ubuntu 
    apt:
      name: apache2
      state: present 